"""The `source.json` contract. See SPEC-ADDENDUM.md section 3.

Generated by extraction and never hand-edited. Anything reading source.json reads
it through these models, so a field rename breaks loudly here rather than quietly
three modules away.
"""

from datetime import UTC, datetime
from typing import Literal

from pydantic import BaseModel, Field, field_validator

from paperboard.geometry import Rect

SCHEMA_VERSION = 1


class PageInfo(BaseModel):
    index: int = Field(ge=0)
    width: float = Field(gt=0)
    height: float = Field(gt=0)
    rotation: int = 0


class PageRect(BaseModel):
    """A rectangle on a page. Page is 0-indexed; geometry is per addendum section 2."""

    page: int = Field(ge=0)
    rect: Rect

    @field_validator("rect")
    @classmethod
    def _corners_must_be_ordered(cls, value: Rect) -> Rect:
        x0, y0, x1, y1 = value
        if not (x0 < x1 and y0 < y1):
            raise ValueError(f"rect must have x0 < x1 and y0 < y1, got {value!r}")
        return value


class Section(BaseModel):
    id: str
    number: str | None = None
    depth: int = Field(default=1, ge=1)
    title: str
    heading_rect: PageRect
    extent: list[PageRect] = []
    text: str = ""


FigureConfidence = Literal["region", "image", "drawings"]


class Figure(BaseModel):
    id: str
    kind: Literal["figure", "table"]
    label: str | None = None
    caption: str = ""
    caption_rect: PageRect | None = None
    rect: PageRect
    confidence: FigureConfidence


class PageText(BaseModel):
    page: int = Field(ge=0)
    text: str


# Layout labels for page furniture: running heads, page numbers, footnotes and
# captions. Never a section heading, never part of a section's extent or of a
# chunk rebuilt from regions.
FURNITURE = {"page-header", "page-footer", "footnote", "caption"}


class LayoutRegion(BaseModel):
    """One labelled layout box. Stored for the snap rule in SPEC-ADDENDUM.md section 5.3
    and nothing else: the API must not re-run the layout model per request."""

    page: int = Field(ge=0)
    rect: Rect
    label: str


class SourceDocument(BaseModel):
    schema_version: int = Field(default=SCHEMA_VERSION, alias="schema")
    paper_id: str
    extracted_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    extractor: str
    pages: list[PageInfo]
    sections: list[Section] = []
    figures: list[Figure] = []
    regions: list[LayoutRegion] = []
    page_text: list[PageText] = []

    model_config = {"populate_by_name": True}
